name: Tencent Cloud Base Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}

      - name: Install dependency and build
        run: |
          corepack enable
          pnpm i
          pnpm build

      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      - name: Push to Cloudbase
        uses: TencentCloudBase/cloudbase-action@v2.0.1
        with:
          # 云开发 secretId
          secretId: ${{SECRETS.SID}}
          # 云开发 secretKey
          secretKey: ${{SECRETS.SKEY}}
          # 云开发环境 Id
          envId: ${{SECRETS.ENVID}}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1